### ISSUE TITLE
Add `time-grunt` as a debug task

### ISSUE THREAD

**Issue by desrosj** [bu-ist/responsive-child-starter#18]
In [responsive-framework #316](https://github.com/bu-ist/responsive-framework/pull/316), we added a time reporting package to Grunt.

It would be nice if this could be in the starter theme, but not run by default (maybe on `grunt build` only, or `grunt debug`).

**Comment by ashleykolodziej** [comment]
Took a look into this and unfortunately it's not really how `time-grunt` is built to work - you pop a line at the beginning of the gruntfile and it monitors all tasks, so there's no real way to run it on a task by task basis. Given that the package is no longer maintained and we are moving away from grunt anyway, I am closing this issue.
