### ISSUE TITLE
Automatically update text domain

### ISSUE THREAD

**Issue by desrosj** [bu-ist/responsive-child-starter#33]
Several version constants have been configured to update dynamically based on the project version in the `package.json` file. Another string that has the potential to be forgotten is the theme's text domain.

If possible, automatically updating this based on the `package.json` project name would be 👌.

**Comment by ashleykolodziej** [comment]
I figured out how to do this over in Responsive Foundation! It's actually super easy. You read the package.json file into Grunt as a variable, and then just use it wherever you need it.
